---
collections:
  - name: community.general
    version: 4.1.0
    source: https://galaxy.ansible.com
  - name: community.hashi_vault
    version: 1.1.3
    source: https://galaxy.ansible.com
  - name: ansible.utils
    version: 2.6.0
    source: https://galaxy.ansible.com
